/** Имена IPC-каналов. Держим в одном месте, чтобы main и preload не разъезжались. */
export const CH = {
  configGet: 'config:get',
  configSave: 'config:save',
  configPatch: 'config:patch',
  configUpsertService: 'config:upsertService',
  configRemoveService: 'config:removeService',
  configUpsertEnv: 'config:upsertEnv',
  configReorderServices: 'config:reorderServices',
  configChanged: 'config:changed',

  secretsAvailable: 'secrets:available',
  secretsList: 'secrets:list',
  secretsSet: 'secrets:set',
  secretsDelete: 'secrets:delete',
  secretsReveal: 'secrets:reveal',
  secretsVerify: 'secrets:verify',
  secretsHas: 'secrets:has',
  secretsCopy: 'secrets:copy',

  envStatus: 'env:status',
  envProbe: 'env:probe',
  envClearSession: 'env:clearSession',
  envChanged: 'env:changed',
  /** Main → renderer: подключить контур из трея (нужен OTP / тосты). */
  envTrayAction: 'env:trayAction',

  vpnConnect: 'vpn:connect',
  vpnDisconnect: 'vpn:disconnect',
  vpnConnectBoth: 'vpn:connectBoth',
  vpnVerifyAll: 'vpn:verifyAll',
  vpnDiscoverCheckpoint: 'vpn:discoverCheckpoint',
  vpnSnxAvailable: 'vpn:snxAvailable',
  vpnSnxLoginTypes: 'vpn:snxLoginTypes',
  vpnSnxOpenInstaller: 'vpn:snxOpenInstaller',
  dnsCapture: 'vpn:dnsCapture',
  dnsApply: 'vpn:dnsApply',
  dnsClear: 'vpn:dnsClear',

  viewShow: 'view:show',
  viewHide: 'view:hide',
  viewRestore: 'view:restore',
  viewBounds: 'view:bounds',
  viewReload: 'view:reload',
  viewBack: 'view:back',
  viewHome: 'view:home',
  viewUrl: 'view:url',
  viewCapture: 'view:capture',
  viewFreeze: 'view:freeze',
  viewDevTools: 'view:devtools',
  /** Полный запрет показа вебвью: блокировка экрана и заставка. */
  viewSuppress: 'view:suppress',
  /** Main → renderer: вебвью грузится (для спиннера в хроме). */
  viewLoading: 'view:loading',
  viewLoadingChanged: 'view:loadingChanged',

  /* Встроенный браузер. Вкладки живут в main рядом со своими WebContentsView,
     рендерер рисует только хром и получает состояние через browserChanged. */
  browserState: 'browser:state',
  browserNewTab: 'browser:newTab',
  browserCloseTab: 'browser:closeTab',
  browserActivateTab: 'browser:activateTab',
  browserMoveTab: 'browser:moveTab',
  browserNavigate: 'browser:navigate',
  browserBack: 'browser:back',
  browserForward: 'browser:forward',
  browserReload: 'browser:reload',
  browserStop: 'browser:stop',
  browserHome: 'browser:home',
  browserDevTools: 'browser:devtools',
  browserBookmark: 'browser:bookmark',
  browserChanged: 'browser:changed',

  itemsQuery: 'items:query',
  itemsSearch: 'items:search',
  itemsChanged: 'items:changed',
  itemsMarkRead: 'items:markRead',
  mailGet: 'mail:get',
  mailSend: 'mail:send',
  mailMarkRead: 'mail:markRead',
  mailListFolders: 'mail:listFolders',
  mailListFoldersForRules: 'mail:listFoldersForRules',
  mailCreateFolder: 'mail:createFolder',
  mailMove: 'mail:move',
  mailListRules: 'mail:listRules',
  mailUpsertRule: 'mail:upsertRule',
  mailDeleteRule: 'mail:deleteRule',
  mailSetRuleEnabled: 'mail:setRuleEnabled',
  mailRulesSupported: 'mail:rulesSupported',
  calendarRespond: 'calendar:respond',
  calendarCreate: 'calendar:create',
  calendarUpdate: 'calendar:update',
  calendarCancel: 'calendar:cancel',
  calendarDetails: 'calendar:details',
  calendarSuggestPeople: 'calendar:suggestPeople',
  contactsSuggest: 'contacts:suggest',
  calendarSchedule: 'calendar:schedule',
  tasksTransition: 'tasks:transition',
  tasksBoard: 'tasks:board',
  todosList: 'todos:list',
  todosCreate: 'todos:create',
  todosUpdate: 'todos:update',
  todosRemove: 'todos:remove',

  automationsList: 'automations:list',
  automationsGet: 'automations:get',
  automationsUpsert: 'automations:upsert',
  automationsDelete: 'automations:delete',
  automationsSetEnabled: 'automations:setEnabled',
  automationsRunNow: 'automations:runNow',
  automationsStepTypes: 'automations:stepTypes',
  automationsChanged: 'automations:changed',

  syncNow: 'sync:now',
  diagnose: 'service:diagnose',
  grabSessionToken: 'service:grabSessionToken',
  logsRead: 'logs:read',
  logsReveal: 'logs:reveal',
  faviconGet: 'icon:favicon',

  bookmarksList: 'bookmarks:list',
  bookmarksAdd: 'bookmarks:add',
  bookmarksAddFromService: 'bookmarks:addFromService',
  bookmarksRemove: 'bookmarks:remove',
  bookmarksChanged: 'bookmarks:changed',

  openPage: 'app:openPage',
  openRoute: 'app:openRoute',
  joinMeeting: 'app:joinMeeting',
  /** Main → renderer: окно развёрнуто / полный экран (светофор скрыт). */
  windowMaximizedChanged: 'window:maximizedChanged',
  /** Main → renderer: ⌘` / ⌘⇧` из вебвью — листать окна стола. */
  deskCycleWindow: 'desk:cycleWindow',
  /** Main → renderer: отпустили ⌘/Ctrl в вебвью — подтвердить switcher. */
  deskConfirmCycleWindow: 'desk:confirmCycleWindow',
  notifyTest: 'app:notifyTest',
  mcpInfo: 'mcp:info',
  mcpAgents: 'mcp:agents',
  mcpConnect: 'mcp:connect',

  notesTree: 'notes:tree',
  notesRead: 'notes:read',
  notesWrite: 'notes:write',
  notesCreate: 'notes:create',
  notesCreateFolder: 'notes:createFolder',
  notesRename: 'notes:rename',
  notesDelete: 'notes:delete',
  notesSearch: 'notes:search',
  notesBacklinks: 'notes:backlinks',
  notesResolveLink: 'notes:resolveLink',
  notesPickVault: 'notes:pickVault',
  notesRevealVault: 'notes:revealVault',

  fsList: 'fs:list',
  fsFavorites: 'fs:favorites',
  fsOpen: 'fs:open',
  fsReveal: 'fs:reveal',
  fsMkdir: 'fs:mkdir',
  fsRename: 'fs:rename',
  fsTrash: 'fs:trash',
  fsPickFolder: 'fs:pickFolder',
  fsDragStart: 'fs:dragStart',
  fsHome: 'fs:home',

  themeSet: 'theme:set',
  themeChanged: 'theme:changed',
  pickFile: 'app:pickFile',
  pickImage: 'app:pickImage',
  openExternal: 'app:openExternal',
  openApp: 'app:openApp',
  appGetVersion: 'app:getVersion',
  updateCheck: 'update:check',
  updateOpen: 'update:open',
  updateAvailable: 'update:available',

  /** Встроенный терминал (node-pty → zsh). */
  terminalCreate: 'terminal:create',
  terminalWrite: 'terminal:write',
  terminalResize: 'terminal:resize',
  terminalKill: 'terminal:kill',
  terminalData: 'terminal:data',
  terminalExit: 'terminal:exit',

  keyboardLayoutGet: 'keyboard:layoutGet',
  keyboardLayoutChanged: 'keyboard:layoutChanged'
} as const
